![](../docs/banner.png)

# NumPy


## Exercises

### 1.

Import numpy under the alias `np`.

In [1]:
# Your answer here
import numpy as np

### 2.

Create the following arrays:

1. Create an array of 5 zeros.
2. Create an array of 10 ones.
3. Create an array of 5 3.141s.
4. Create an array of the integers 1 to 20.
5. Create a 5 x 5 matrix of ones with a dtype `int`.

In [2]:
# Your answer here.
zeros = np.array([0, 0, 0, 0, 0])
print(len((zeros)))

5


In [3]:
#Create an array of 10 ones
ones = np.ones(10)
print(ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [4]:
#Create an array of 5 3.141s
record = np.array([3.141, 3.141, 3.141, 3.141, 3.141])
print(record)


[3.141 3.141 3.141 3.141 3.141]


In [5]:
#Create an array of the integers 1 to 20
num1 = np.arange(1, 21)

print(type((num1)))
print(num1)
num1.dtype

<class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


dtype('int32')

In [6]:
#Create a 5 x 5 matrix of ones with a dtype int

matrix_5 = np.ones((5, 5), dtype=int)
print(matrix_5)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


### 3.

Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

In [7]:
# Your answer here.
#Create a 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution
matrix_3D = np.random.randn(3, 3, 3)
print(matrix_3D)


[[[ 3.35176754e-01 -6.66058446e-01 -7.58435456e-02]
  [ 1.35549871e+00  2.27442986e+00  6.86086309e-01]
  [-1.25631121e+00 -6.80071472e-01  6.30845969e-01]]

 [[-7.25743164e-02  4.71073639e-01 -8.75003398e-01]
  [-1.25078703e-01 -8.36026499e-01  1.44442014e-03]
  [ 1.80723028e+00  4.09500568e-01 -2.67644568e-01]]

 [[ 5.31508610e-01  3.40206980e-01  2.18661064e+00]
  [ 7.22418401e-01 -1.28843495e+00 -2.62737621e+00]
  [ 1.41857430e+00  2.98875018e-01  5.01406634e-01]]]


In [8]:
#Reshape the above array into shape (27,)
reshape = matrix_3D.reshape((27,))

print(reshape)


[ 3.35176754e-01 -6.66058446e-01 -7.58435456e-02  1.35549871e+00
  2.27442986e+00  6.86086309e-01 -1.25631121e+00 -6.80071472e-01
  6.30845969e-01 -7.25743164e-02  4.71073639e-01 -8.75003398e-01
 -1.25078703e-01 -8.36026499e-01  1.44442014e-03  1.80723028e+00
  4.09500568e-01 -2.67644568e-01  5.31508610e-01  3.40206980e-01
  2.18661064e+00  7.22418401e-01 -1.28843495e+00 -2.62737621e+00
  1.41857430e+00  2.98875018e-01  5.01406634e-01]


### 4.

Create an array of 20 linearly spaced numbers between 1 and 10.

In [9]:
# Your answer here.
#Create an array of 20 linearly spaced numbers between 1 and 10
dense = np.linspace(1, 10, 20)
print(dense)


[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


### 5.

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [10]:
import numpy as np
a = np.arange(1, 26).reshape(5, -1)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


```python
20
```

In [11]:
# Your answer here.
print(a[1:5, 3:5])

[[ 9 10]
 [14 15]
 [19 20]
 [24 25]]


```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [12]:
# Your answer here.
print(a[1:2 ,])

[[ 6  7  8  9 10]]


```python
array([ 6,  7,  8,  9, 10])
```

In [13]:
# Your answer here.
print(a)
print()
print(a[2:4 , :])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

[[11 12 13 14 15]
 [16 17 18 19 20]]


```python
array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])
```

In [14]:
# Your answer here.
print(a)
print()
print(a[1:3, 2:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

[[ 8  9]
 [13 14]]


```python
array([[ 8,  9],
       [13, 14]])
```

### 6.

Calculate the sum of all the numbers in `a`.

In [16]:
# Your answer here.
print(a)
print()
a_add = a.sum()
print('The sum of all the numbers in the array is', a_add)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

The sum of all the numbers in the array is 325


### 7.

Calculate the sum of each row in `a`.

In [17]:
# Your answer here.
print(a)
print()
a_sumrow = a.sum(axis= 1)
print('The sum of each row is ', a_sumrow)



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

The sum of each row is  [ 15  40  65  90 115]


### 8.

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [18]:
# Your answer here.
print(a)
print()
a_mean = a.mean()
print('The mean value of a is:', a_mean)

mask = a > a_mean
print('The values are: ', mask)
print()

extract = a[mask]
print('The extracted masked values greater than the mean value are: ', extract )

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

The mean value of a is: 13.0
The values are:  [[False False False False False]
 [False False False False False]
 [False False False  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]

The extracted masked values greater than the mean value are:  [14 15 16 17 18 19 20 21 22 23 24 25]


### 9.

Find the location of the minimum value in the following array `b`:

In [19]:
np.random.seed(123)
b = np.random.randn(10)
print(b)
print()
print('let us our set index')
print()
set_index = np.arange(10)

b_index = np.column_stack((set_index, b))

print('our indexed value are: ', b_index)


[-1.0856306   0.99734545  0.2829785  -1.50629471 -0.57860025  1.65143654
 -2.42667924 -0.42891263  1.26593626 -0.8667404 ]

let us our set index

our indexed value are:  [[ 0.         -1.0856306 ]
 [ 1.          0.99734545]
 [ 2.          0.2829785 ]
 [ 3.         -1.50629471]
 [ 4.         -0.57860025]
 [ 5.          1.65143654]
 [ 6.         -2.42667924]
 [ 7.         -0.42891263]
 [ 8.          1.26593626]
 [ 9.         -0.8667404 ]]


In [20]:
# Your answer here.
min_value = b_index.min()
print('The minimum value is:', min_value)
print()
min_index = b.argmin()
print('The location of the minimum value is the', min_index, 'location')
print('convert to 2D')
loc_2D = np.unravel_index(min_index, b.shape)
print('The location of the minmum value in 1D is ', loc_2D)

The minimum value is: -2.426679243393074

The location of the minimum value is the 6 location
convert to 2D
The location of the minmum value in 1D is  (6,)


### 10.

Find the location of the maximum value in the following 2D array `c` (hint: there are many ways to do this question, but a quick search on stackoverflow.com will typically help you find the optimum solution for a problem, for example see [post](https://stackoverflow.com/questions/3584243/get-the-position-of-the-biggest-item-in-a-multi-dimensional-numpy-array)):

In [21]:
np.random.seed(123)
c = np.random.randn(3, 2)
print(c)
print()

[[-1.0856306   0.99734545]
 [ 0.2829785  -1.50629471]
 [-0.57860025  1.65143654]]



In [22]:
# Your answer here.
max_value = c.argmax()
max_loc = np.unravel_index(max_value, c.shape)
print('The location is ', max_loc)


The location is  (2, 1)


<hr>
<hr>
<hr>